name: Linting
on: push

jobs:
  lint-backend:
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pylint
        uses: cclauss/GitHub-Action-for-pylint@master
        with:
          args: pip install -r requirements.txt ; pylint *.py
